export * from '../../modules/Department/DepartmentModel'
export * from '../../modules/Company/CompanyModel'
export * from '../../modules/Hospital/HospitalModel'
export * from '../../modules/Label/LabelModel'
export * from '../../modules/Role/RoleModel'
export * from '../../modules/User/UserModel'
