export enum StatusOfBookingEnum {
  BOOKED = 'BOOKED',
  ENTERED = 'ENTERED',
  LEFT = 'LEFT',
  AWAITING_ENTERING = 'AWAITING_ENTERING',
  AWAITING_LEAVING = 'AWAITING_LEAVING',
  AWAITING_BOOKING = 'AWAITING_BOOKING',
}

export enum TypeOfBookingEnum {
  INDIVIDUAL = 'INDIVIDUAL',
  REPAIR = 'REPAIR',
  GROUP = 'GROUP',
  INTERNET_WEB = 'INTERNET_WEB',
  INTERNET_CHATBOT = 'INTERNET_CHATBOT',
}

export enum SourceFundingEnum {
  PUBLIC_INSURANCE = 'PUBLIC_INSURANCE',
  PRIVATE_INSURANCE = 'PRIVATE_INSURANCE',
  PAID_BY_CITIZENS = 'PAID_BY_CITIZENS',
  PAID_BY_COMPANY = 'PAID_BY_COMPANY',
  CHARITY = 'CHARITY',
  BUDGET_FEDERAL = 'BUDGET_FEDERAL',
  BUDGET_REGION = 'BUDGET_REGION',
  BUDGET_DISTRICT = 'BUDGET_DISTRICT',
  COLLECTIVE_FUNDING_FSS = 'COLLECTIVE_FUNDING_FSS',
  OTHER = 'OTHER',
  NONE = 'NONE',
}
